language: perl
perl:
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq hmmer emboss

script: perl Makefile.PL && make && make test

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master